services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    environment:
      MPLCONFIGDIR: /app/config
      MNIST_MODEL_PATH: ./model/vit-base-mnist
    volumes:
      - ./backend/src:/app
  frontend:
    build: frontend
    ports:
      - "8501:8501"
    environment:
      URL_BACKEND: http://backend:8000/
    volumes:
      - ./frontend/src:/app
    depends_on:
      - backend

